### PR TITLE
Fixed Timeshift and Moving Average on 0.0.5

### PR DESCRIPTION
**Pull request by drsoares**
Issue fix, #122. Inside **TimeShift** functions and **MovingAverage** there were some results not wrapped into promises leading into the following issues:
  
Screenshot 2021-03-09 at 21 55 35
Screenshot 2021-03-09 at 21 56 08

**Datasource**: OpenTSDB

### CODE REVIEW

**Comment by Gauravshah** [comment]
@ShilpaSivanesan had we not fixed this as part of previous PR ?

**Comment by ShilpaSivanesan** [comment]
> @ShilpaSivanesan had we not fixed this as part of previous PR ?

Yes I added this at `this.query`
here is the PR https://github.com/GoshPosh/grafana-meta-queries/pull/118

@drsoares added this specifically for timeshift.
But our fix should handle this

**Comment by drsoares** [comment]
Those two parts were missing and not working for OpenTSDB at least. Inside timeshift and movingaverage methods, please double check.

**Comment by drsoares** [comment]
Some other datasources are experiencing the same problem.

https://github.com/GoshPosh/grafana-meta-queries/issues/124#issuecomment-796764442

**Comment by xpatos** [comment]
I can confirm that this fix works in my case for elastic search. I just applied the fix in Chrome Dev tools. Please merge this PR.

**Comment by Gauravshah** [comment]
@drsoares can you help me understand why does this fix things ?
we are converting all before sending it to grafana https://github.com/GoshPosh/grafana-meta-queries/blob/c9042c96b8503cea337188ad543a7c55086a26ce/src/datasource.js#L89

**Comment by earth08** [comment]
Not working on grafana 7.4.5 with influxdb

**Comment by xpatos** [comment]
@drsoares Can you please help @Gauravshah understand what is the problem so our graphs can start working again.

**Comment by earth08** [comment]
I started using autohome-comparequeries after waiting so long

**Comment by drsoares** [comment]
Apologies for the long absence. @earth08 do you mean this change or the plugin before the change?

@Gauravshah I think the best explanation is trying to reproduce the error with the mentioned datasources. (influx, opentsdb and elasticsearch) I wonder if there's any in which this plugin is working, not sure if there are any behavioural diferences bettween the query datasources from different plugins, the contract is the same and never returns a promise, it results an observable. I've just let that if statement to make it consistent with the remaining plugin.
Cheers

**Comment by earth08** [comment]
@drsoares 
I have never got it working,
In my case arithmetic is working, but timeshif doesnt

**Comment by drsoares** [comment]
@earth08 but have you tried with this patch? Without these changes only arithmetic was working for me as well.
Cheers

**Comment by earth08** [comment]
@drsoares which patch,
As I only see 0.0.5 version
And time shift is not working

**Comment by giom-l** [comment]
I confirm this fix perfectly works with grafana 7.5.2 and metaqueries 0.0.5 (tested with timeshift)

**Comment by xpatos** [comment]
Since @Gauravshah seems reluctant to merge this fix, can we create a fork or use a branch or something. Many graphs in our company is broken due to this bug. It has soon been two months since this bug was reported.

**Comment by garyhodgson** [comment]
Can also confirm that manually applying the change in this PR and restarting grafana got timeshift to work again (grafana 7.5.5)

**Comment by earth08** [comment]
How to apply and what change are u talking about?

**Comment by garyhodgson** [comment]
> How to apply and what change are u talking about?

I just applied the changes detailed here: https://github.com/GoshPosh/grafana-meta-queries/pull/128/files

* On the grafana server go to the plugins folder. 
* In the grafana-meta-queries folder is a file called datasource.js. Open this file in an editor.
* Go to line 202 where it says "return ds.query(options)" and replace it with text: 
```
var ds_res = ds.query(options);
if(ds_res.then){
    return ds_res;
}
else{
    return ds_res.toPromise();
}
```
* do the same for line 271.
* restart grafana.

**Comment by Gauravshah** [comment]
@drsoares can you remove some of recent commits so that this PR can be merged.  we have another competing PR here https://github.com/GoshPosh/grafana-meta-queries/pull/132 was trying to avoid merge that

**Comment by ShilpaSivanesan** [comment]
@drsoares could you please pull the latest master and update this PR
Also please push dist/datasource.js

**Comment by ShilpaSivanesan** [comment]
https://github.com/GoshPosh/grafana-meta-queries/pull/141

**Comment by giom-l** [comment]
I still don't understand why this issue is closed.
I installed tag 0.0.8 some minutes ago, and I still hit the same issue
```
runRequest.catchError TypeError: data is undefined
    promise https://grafana/public/plugins/goshposh-metaqueries-datasource/datasource.js:322
```

When I apply the path in datasource.js, ie 
replace 
```
 return ds.query(options);
```
with 
```
var ds_res = ds.query(options);
if (ds_res.then){
    return ds_res;
}
else {
    return ds_res.toPromise();
}
```
on lines 301 & 232
everything is working really fine.

For the record, I'm using `timeshift`  function here

**Comment by giom-l** [comment]
I added a new PR to integrate changes proposed by @drsoares  based on uptodate master branch.
I also added some stuffs in docker-compose for testing
#145

**Pull request merged**
