### PR TITLE
add Unit to TimeShift

### PR DESCRIPTION
**Pull request by japatel**
Have added the following to the TimeShift Plugin:

- On the UI user can input the TimeShift Unit in hours,days,weeks. This is clubbed with the periods parameter. This provides us to get more granular option on the graph v/s only days.

- Have modified the plugin to show the Day-over-Day graph a shifted forward in time, when positive periods are entered. Made the graph look the same as timeshift proxy on InfluxDB.

- Limited the user to provide only positive value for TimeShift.

- Limited the datapoints passed to the grafana graphs to be <= toRAW. This way grafana is not showing the max values which might be not in the range of the graph.

### CODE REVIEW

**Comment by Gauravshah** [comment]
thanks for the contribution @japatel .
can you separate this to 4 different PR so that it can merged at its pace ?
For example. I agree with following

> Have modified the plugin to show the Day-over-Day graph a shifted forward in time, when positive periods are entered. Made the graph look the same as timeshift proxy on InfluxDB.
But then we need to  think about existing graphs

> 
Limited the user to provide only positive value for TimeShift.

I do not think that this restriction adds value. There are use cases where shifting forward helps, especially on cohort

**Comment by japatel** [comment]
Hi Gaurav,
I will separate them into 4 PRs.

**Comment by wufengqiyun** [comment]
I try to add the code to my plugin and find that the 'Period' is changed to be > 0 (author changed 'add' to 'substract'),and it caused the panel  wrong.After I keep the 'add' as before, the panel restored.

**Comment by Gauravshah** [comment]
closing this
PR for timeshift units : https://github.com/GoshPosh/grafana-meta-queries/pull/61

**Pull request closed without merging**
